//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoListApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskRecord
    {
        public int RecordID { get; set; }
        public int TaskID { get; set; }
        public int UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
    
        public virtual Chore Chore { get; set; }
    }
}
